#ifndef SMARTHOME_HAL_KEYPAD_KEYPAD_INTERFACE_H_
#define SMARTHOME_HAL_KEYPAD_KEYPAD_INTERFACE_H_


void KeyPad_VidInit(u8 LOC_u8Port);
u8 GetPressedKey(u8 LOC_u8Port);

#endif  /* SMARTHOME_HAL_KEYPAD_KEYPAD_INTERFACE_H_ */
